[package]
name = "read-pftrace"
version = "0.1.0"
authors = ["mark <markm@cs.wisc.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
hdrhistogram = "7.2.0"
structopt = "0.3.21"

